### PR TITLE
ENH: Include cert chain

### PR DESCRIPTION
**Pull request by thermokarst**

### CODE REVIEW

**Comment by jakereps** [comment]
@thermokarst When a template runs the `{% load static %}` is this cert being downloaded and sent to everyone's browser resources by being in the static folder?

**Comment by thermokarst** [comment]
Good question. No, the {% load static %} [tag](https://docs.djangoproject.com/en/1.10/ref/templates/builtins/#std:templatetag-load) just loads the {% static %} tag for us to use.

**Comment by jakereps** [comment]
👍  K cool, not that it'd really matter being there, but just the unnecessary bandwidth.

**Comment by thermokarst** [comment]
But, I am totally up for stashing the bundle somewhere else. This just seemed convenient, but not particularly appropriate.

**Pull request merged**
